# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1af892c08c3d7bcfa6ba7780526a65b94096edbda2486dda086449b5dd3769ba83982311a1316a2195e945f116488260608b869d77faa87851437e6a3d06d768

test:
  secret_key_base: d2e0a1fb63a941feb3e735f231528c3fb1c3df4776bf98c9cc79878e2811f2b8434eee9ada1b2467dafe4f6ed5936bddf72fc51a8535da99898a9e8b4bf48654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
